spring.datasource.url=jdbc:sqlite:properties.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# SQLite doesn't support Spring's default connection validation query -
# this avoids startup errors caused by that mismatch.
spring.datasource.hikari.connection-test-query=SELECT 1
